export const offers = [
  {
    title: 'Jaipur Heritage Escape',
    slug: 'jaipur-heritage-escape',
    subtitle: 'A short Pink City break',
    summary: 'Forts, bazaars and royal stays in three unhurried days.',
    duration: '3 Days / 2 Nights',
    destinations: ['Jaipur'],
    originalPrice: 16900,
    discountType: 'none',
    discountValue: 0,
    status: 'active',
    featured: false,
    sortOrder: 1,
  },
  {
    title: 'Desert to Palace',
    slug: 'desert-to-palace',
    subtitle: 'Golden sands to lake palaces',
    summary: 'From Jaisalmer dunes to the blue city and the lakes of Udaipur.',
    duration: '6 Days / 5 Nights',
    destinations: ['Jaisalmer', 'Jodhpur', 'Udaipur'],
    originalPrice: 32900,
    discountType: 'none',
    discountValue: 0,
    status: 'active',
    featured: false,
    sortOrder: 2,
  },
  {
    title: 'Udaipur & Mount Abu Retreat',
    slug: 'udaipur-mount-abu-retreat',
    subtitle: 'Lakes and hill air',
    summary: 'Slow days on Lake Pichola followed by the cool hills of Mount Abu.',
    duration: '5 Days / 4 Nights',
    destinations: ['Udaipur', 'Mount Abu'],
    originalPrice: 28900,
    discountType: 'none',
    discountValue: 0,
    status: 'active',
    featured: false,
    sortOrder: 3,
  },
];
